import { mkdir, readFile, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { r2Config, r2Delete, r2Exists, r2Get, r2Put } from "./r2";

/**
 * Where the bytes physically go, and nothing else.
 *
 * Four operations on an opaque key. Everything that makes a stored file *safe*
 * — the generated key, encryption, the size cap, the MIME allowlist and the
 * content-signature check — stays in `blob-store.ts`, above this line. That
 * matters more than it looks: a backend cannot weaken any of those by being
 * written badly, and adding a third one later cannot forget to encrypt.
 *
 * The filesystem backend is the default and the only one preview mode or CI
 * ever uses. Production sets the four R2 variables and gets object storage,
 * which is what stops a Render deploy destroying every uploaded case file —
 * the container's disk does not survive a restart, so the local backend on a
 * host without a mounted volume loses data silently.
 */

export type BlobBackend = {
  readonly name: "filesystem" | "r2";
  /** A short description for the health endpoint and the boot log. */
  readonly describe: string;
  put(key: string, bytes: Buffer): Promise<void>;
  get(key: string): Promise<Buffer>;
  exists(key: string): Promise<boolean>;
  remove(key: string): Promise<void>;
};

/* ── Filesystem ─────────────────────────────────────────────────────────── */

export function storageRoot(): string {
  return resolve(process.env["FILE_STORAGE_DIR"]?.trim() || ".file-storage");
}

/**
 * Resolve a key inside the storage root, or refuse.
 *
 * Keys are generated by us and never client-supplied, so this cannot currently
 * be reached with a hostile value. It stays because path handling is where this
 * class of bug always hides, and the guard costs one comparison.
 */
function keyToPath(key: string): string {
  const root = storageRoot();
  const full = resolve(join(root, key));
  if (full !== root && !full.startsWith(root + sep)) {
    throw new Error("storage key escapes the storage root");
  }
  return full;
}

export const filesystemBackend: BlobBackend = {
  name: "filesystem",
  describe: "local filesystem",

  async put(key, bytes) {
    const full = keyToPath(key);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, bytes, { mode: 0o600 });
  },

  async get(key) {
    return readFile(keyToPath(key));
  },

  async exists(key) {
    try {
      return (await stat(keyToPath(key))).isFile();
    } catch {
      return false;
    }
  },

  async remove(key) {
    try {
      await unlink(keyToPath(key));
    } catch {
      // Already gone is the desired end state.
    }
  },
};

/* ── Selection ──────────────────────────────────────────────────────────── */

/**
 * Resolved per call rather than cached at import.
 *
 * The same reason `encryptionKey()` is: a module-level constant freezes
 * whatever the environment looked like when the module was first required,
 * which makes the startup guards untestable and surprises anyone who changes a
 * variable expecting a restart to pick it up.
 */
export function blobBackend(): BlobBackend {
  const config = r2Config();
  if (!config) return filesystemBackend;

  return {
    name: "r2",
    describe: `Cloudflare R2 bucket "${config.bucket}"`,
    put: (key, bytes) => r2Put(config, key, bytes),
    get: (key) => r2Get(config, key),
    exists: (key) => r2Exists(config, key),
    remove: (key) => r2Delete(config, key),
  };
}

/**
 * Say at boot which store is in use, and warn when it is one that forgets.
 *
 * A container filesystem with no mounted volume loses every uploaded file on
 * the next deploy or restart. That is invisible until a chamber tries to open
 * a filing weeks later, so it is worth a line in the log every time rather
 * than a note in a runbook nobody reads during setup.
 */
export function describeBlobBackend(): { backend: string; ephemeralRisk: boolean } {
  const backend = blobBackend();
  return {
    backend: backend.describe,
    ephemeralRisk: backend.name === "filesystem" && process.env["NODE_ENV"] === "production",
  };
}
