/**
 * Speech-to-text for consultation recordings.
 *
 * No transcription provider is wired up yet. In preview mode a deterministic
 * sample transcript is produced so the recorder flow can be exercised end to
 * end; with a real deployment and no provider configured the call reports that
 * transcription is pending rather than fabricating content that would look like
 * a genuine record of what a client said.
 */

import { isPreviewAuth } from "./preview-mode";

export type TranscriptionResult = {
  audioUrl: string | null;
  transcript: string;
};

const SAMPLE_BY_CATEGORY: Record<string, string[]> = {
  legal_solution: [
    "Advocate: Thank you for coming in. I want to walk you through what the succession petition will require.",
    "Client: I have the death certificate, but not the notarised affidavit yet.",
    "Advocate: That affidavit is the item holding up the filing. I will raise a document request today so it is tracked.",
    "Client: How long after that until we are listed?",
    "Advocate: Once filed, listing typically follows in three to four weeks. I will confirm the date as soon as the registry allots it.",
  ],
  regulatory_solution: [
    "Advocate: We reviewed the order-in-original. The demand rests on a classification the department has since revised.",
    "Client: Does that help our appeal?",
    "Advocate: It does. We will plead the revised circular and press for a stay on recovery pending the appeal.",
    "Client: What is our exposure if the stay is refused?",
    "Advocate: Principal plus interest. I will circulate a written note quantifying it before the hearing.",
  ],
  business_consultation: [
    "Advocate: On the proposed restructuring, the main question is whether the transfer attracts stamp duty in this state.",
    "Client: We assumed it would be exempt.",
    "Advocate: The exemption is narrower than it reads. I will set out the conditions in writing so you can plan around them.",
  ],
  procedural_compliance: [
    "Advocate: The filing checklist has three outstanding items — the index, the vakalatnama and the certified copies.",
    "Client: I can arrange the certified copies this week.",
    "Advocate: Good. My clerk will prepare the index and paperbook in parallel.",
  ],
};

function sampleTranscript(category: string, title: string): string {
  const lines = SAMPLE_BY_CATEGORY[category] ?? SAMPLE_BY_CATEGORY.legal_solution;
  const header = `Consultation: ${title}\nGenerated by preview transcription — sample content, not a real recording.\n`;
  return `${header}\n${lines.join("\n")}`;
}

export async function transcribeConsultation(input: {
  consultationId: number;
  title: string;
  category: string;
}): Promise<TranscriptionResult> {
  if (isPreviewAuth()) {
    return {
      // Points at this server's own (unimplemented) media route rather than an
      // invented external vault URL, so nothing looks like a live asset.
      audioUrl: `/api/consultations/${input.consultationId}/audio`,
      transcript: sampleTranscript(input.category, input.title),
    };
  }

  return {
    audioUrl: null,
    transcript:
      "Transcription pending — no speech-to-text provider is configured for this deployment.",
  };
}
